### ISSUE TITLE
failed to switch gbc cartridges

### ISSUE THREAD

**Issue by Wokann** [AntonioND/gba-switch-to-gbc#1]
hello, I met som problem using the homebrew you made and didn't know how to solve it.
when homebrew mentioned me to swrap cartridge in 10 seconds, I pluged out my gba flashcart and pluged in my gbc cartridge. 
But then it reset to gbc game as normal without the setting set in homebrew.
I wonder how to make it works as you like in the video, or did I lost some other steps need to be done first?

**Comment by Wokann** [comment]
oh, holding L key while swap gb cartridge can switch it successfully. This issue is ending!

**Comment by AntonioND** [comment]
The L button doesn't affect anything, you just have to be very careful when inserting the cartridge. The contacts need to be completely straight. It depends a lot on your luck, to be honest.
